name: Integração Contínua

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Instalar NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Instalar dependências do projeto
      run: npm install

    - name: Executar o Cypress
      run: npm test
    
    - name: Gerar relatório HTML unificado
      run: |
        mkdir -p cypress/reports
        npx mochawesome-merge cypress/reports/*.json > cypress/reports/merged-report.json
        npx marge cypress/reports/merged-report.json -f index -o cypress/reports

    - name: Upload dos relatórios
      uses: actions/upload-artifact@v4
      with:
        name: relatorios
        path: |
          cypress/reports
          cypress/screenshots
          cypress/videos