name: Integração Contínua

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Instalar NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Instalar dependências do projeto
      run: npm install

    - name: Executar o Cypress
      run: npm test