name: Integração Contínua

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Clean reports
        run: npm run clean:reports

      - name: Run tests with reports
        run: npm run test:report

      - name: Merge reports
        run: npm run merge:reports

      - name: Generate HTML report
        run: npm run generate-html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: relatorios
          path: 
            cypress/reports
            cypress/screenshots
            cypress/videos
